tracker/tasktracker/urls.py
from django.conf.urls import url

from . import views

app_name = 'tasktracker'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<task_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^add', views.add, name='add'),
    url(r'^subtask(?P<task_id>[0-9]+)/', views.subtask, name='subtask'),
    url(r'^delete(?P<task_id>[0-9]+)/$', views.delete, name='delete'),
    url(r'^edit(?P<task_id>[0-9]+)/$', views.edit, name='edit'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^complete(?P<task_id>[0-9]+)/$', views.complete, name='complete'),
    url(r'^removeuser/$', views.removeuser, name='removeuser'),
    url(r'^reccurent', views.addreccurenttask, name='reccurent'),
    url(r'^rdelete(?P<task_id>[0-9]+)/$', views.rdelete, name='rdelete'),
    url(r'^redit(?P<task_id>[0-9]+)/$', views.redit, name='redit'),
    url(r'^rdetail(?P<task_id>[0-9]+)/$', views.rdetail, name='rdetail'),
    url(r'^rcomplete(?P<task_id>[0-9]+)/$', views.rcomplete, name='rcomplete'),
    url(r'^show(?P<state>.*)/$', views.show, name='show'),
    url(r'^password/$', views.change_password, name='change_password'),

]

tracker/tracker/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
admin.autodiscover()

urlpatterns = [
    url(r'^tasktracker/', include('tasktracker.urls')),
    url(r'^admin/', admin.site.urls),
]

tracker/tasktracker/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from datetime import datetime
from django.contrib.auth.models import User
from django.db import models
from multiselectfield import MultiSelectField

from .consts import DAYS, State

class Task(models.Model):
    title = models.CharField(max_length=150)
    body = models.TextField()
    deadline = models.DateTimeField(null=True, blank=True)
    group = models.CharField(max_length=150)
    priority = models.CharField(max_length=150)
    state = models.CharField(max_length=150, default=State.NOT_READY)
    timechange = models.DateTimeField(default=datetime.now, blank=True)
    timecreate = models.DateTimeField(default=datetime.now, blank=True)
    subtask = models.BooleanField(default=False)
    parent = models.IntegerField(default=0)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    users = models.ManyToManyField(User, related_name='shared_users', default=None, null=True, blank=True)

    def __str__(self):
        return self.title

class Reccurentask(models.Model):
    title = models.CharField(max_length=150)
    body = models.TextField()
    deadline = models.DateTimeField()
    group = models.CharField(max_length=150)
    priority = models.CharField(max_length=150)
    state = models.CharField(max_length=150, default=State.NOT_READY)
    period = models.IntegerField(null=True, blank=True)
    days = MultiSelectField(choices=DAYS, max_choices=7, max_length=14, blank=True, null=True)
    timechange = models.DateTimeField(default=datetime.now, blank=True)
    timecreate = models.DateTimeField(default=datetime.now, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

tracker/tasktracker/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, logout, update_session_auth_hash
from django.template import RequestContext
from django.contrib import messages
from django.contrib.auth import login as auth_login
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.shortcuts import get_object_or_404, render, redirect
from django.utils import timezone
from django.http.response import HttpResponseBadRequest
from django.utils.datastructures import MultiValueDictKeyError
import dateutil.parser
from dateutil.relativedelta import relativedelta
from datetime import datetime

from .models import Task, Reccurentask
from .consts import State
from .checks import checkfails, checkreccurent

@login_required(login_url='tasktracker:login')
def detail(request, task_id):
    task = get_object_or_404(Task, pk=task_id, users=request.user)
    return render(request, 'tasktracker/detail.html', {'task': task, 'date': timezone.now()})

@login_required(login_url='tasktracker:login')
def index(request):
    current_user = request.user
    checkfails(request)
    checkreccurent(request)
    reccurenttasks = Reccurentask.objects.filter(author=current_user).order_by('-timechange')
    tasks = Task.objects.filter(author=current_user).order_by('-timechange')
    teamtasks = Task.objects.filter(users=current_user).order_by('-timechange')
    context = {'tasks': tasks, 'reccurenttasks': reccurenttasks, 'teamtasks': teamtasks}
    return render(request, 'tasktracker/index.html', context)

@login_required(login_url='tasktracker:login')
def show(request, state):
    current_user = request.user
    tasks = Task.objects.filter(author=current_user, state=state).order_by('-timechange')
    reccurenttasks = Reccurentask.objects.filter(author=current_user, state=state).order_by('-timechange')
    teamtasks = Task.objects.filter(users=current_user, state=state).order_by('-timechange')
    context = {'tasks': tasks, 'reccurenttasks': reccurenttasks, 'teamtasks': teamtasks}
    return render(request, 'tasktracker/index.html', context)

@login_required(login_url='tasktracker:login')
def add(request):
    users = User.objects.all()
    current_user = request.user
    if request.POST :
        try:
            title = request.POST['title']
            body = request.POST['text']
            try:
                deadline = request.POST['deadline']
                if deadline == '':
                    deadline = None
                else:
                    deadline = dateutil.parser.parse(deadline)
                    if deadline < datetime.now():
                        messages.error(request,'Input date is not correct!')
                        return render(request, 'tasktracker/add.html', {'users': users, 'current_user': current_user})
            except ValueError:
                messages.error(request,'Please input correct format of date!')
                return render(request, 'tasktracker/add.html', {'users': users, 'current_user': current_user})
            group = request.POST['group']
            priority = request.POST['priority']
            list = request.POST.getlist('users')
            task = Task(title=title, body=body, deadline=deadline, group=group, priority=priority,author=current_user)
            task.save()
            for user in users:
                if user.username in list:
                    task.users.add(user)
            task.users.add(current_user)
            task.save()
        except MultiValueDictKeyError:
            return HttpResponseBadRequest('Bad Request')

        return redirect('tasktracker:index')
    else:
        return render(request, 'tasktracker/add.html',{'users': users, 'current_user': current_user})

@login_required(login_url='tasktracker:login')
def delete(request, task_id):
    task = get_object_or_404(Task, pk=task_id, author=request.user)
    if request.POST:
        tasks = Task.objects.filter().order_by('-timechange')
        if not task.subtask:
            for subtask in tasks:
                if subtask.parent == task.id:
                    subtask.delete()
        task.delete()
    return redirect('tasktracker:index')

@login_required(login_url='tasktracker:login')
def edit(request, task_id):
    task = get_object_or_404(Task, pk=task_id, users=request.user)
    users = User.objects.all()
    current_user = request.user
    if request.POST :
        try:
            task.title = request.POST['title']
            task.body = request.POST['text']
            try:
                deadline = request.POST['deadline']
                if deadline == '':
                    task.deadline = None
                else:
                    task.deadline = dateutil.parser.parse(deadline)
                    if task.deadline < datetime.now():
                        messages.error(request, 'Input date is not correct!')
                        context = {'task': task, 'deadline': deadline, 'current_user': current_user, 'users': users}
                        return render(request, 'tasktracker/edit.html', context)
            except ValueError:
                messages.error(request,'Please input correct format of date!')
                context = {'task': task, 'deadline': deadline, 'current_user': current_user, 'users': users}
                return render(request, 'tasktracker/edit.html', context)
            task.group = request.POST['group']
            task.priority = request.POST['priority']
            task.timechange = datetime.now()
            task.state = State.NOT_READY
            list = request.POST.getlist('users')
            task.users.set([])
            for user in users:
                if user.username in list:
                    task.users.add(user)
            task.users.add(current_user)
            task.save()
        except MultiValueDictKeyError:
            return HttpResponseBadRequest('Bad Request')

        return redirect('tasktracker:index')
    else:
        if task.deadline:
            deadline = datetime.strftime(task.deadline,'%m/%d/%Y %I:%M %p')
        else:
            deadline = task.deadline
        context = {'task': task, 'deadline': deadline, 'current_user': current_user, 'users': users}
        return render(request, 'tasktracker/edit.html', context)

@login_required(login_url='tasktracker:login')
def subtask(request, task_id):
    parenttask = get_object_or_404(Task, pk=task_id, users=request.user)
    if request.POST :
        try:
            title = request.POST['title']
            body = request.POST['text']
            try:
                deadline = request.POST['deadline']
                if deadline == '':
                    deadline = None
                else:
                    deadline = dateutil.parser.parse(deadline)
                    if deadline < datetime.now():
                        messages.error(request,'Input date is not correct!')
                        return render(request, 'tasktracker/subtask.html', {'task': parenttask})
            except ValueError:
                messages.error(request,'Please input correct format of date!')
                return render(request, 'tasktracker/subtask.html', {'task': parenttask})
            group = request.POST['group']
            priority = request.POST['priority']
            current_user = request.user
            task = Task(title=title, body=body, deadline=deadline, group=group,
                        priority=priority,author=current_user)
            task.subtask = True
            task.parent = task_id
            task.save()
            task.users.set(parenttask.users.all())
            task.save()
        except MultiValueDictKeyError:
            return HttpResponseBadRequest('Bad Request')

        return redirect('tasktracker:index')
    else:
        return render(request, 'tasktracker/subtask.html', {'task': parenttask})

def signup(request):
    if request.POST:
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            auth_login(request, user)
            return redirect('tasktracker:index')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})


def login(request):
    if request.POST:
        logout(request)
        form = AuthenticationForm(request.POST)
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                auth_login(request, user)
                return redirect('tasktracker:index')
        else:
            messages.error(request,'username or password not correct')
            return render(request, 'login.html', {'form': form})

    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})

def change_password(request):
    if request.POST:
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('tasktracker:index')

    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'change_password.html', {'form': form})


@login_required(login_url='tasktracker:login')
def removeuser(request):
    current_user = request.user
    user = get_object_or_404(User, username=current_user)
    user.delete()
    return redirect('tasktracker:index')

@login_required(login_url='tasktracker:login')
def logout_view(request):

tracker/tasktracker/templates/tasktracker/add.html
{% include 'partials/header.html' %}
<font color="white">
<div class="container">
<form action="{% url 'tasktracker:add'  %}" method="post">
{% csrf_token %}
{% for message in messages %}
  <div class="alert alert-success">
    <a class="close" href="#" data-dismiss="alert">×</a>
      {{ message }}
    </div>
{% endfor %}
  <label for="title">Title</label><br />
  <input type="text" name="title" id="title" />
  <br>
  <label for="text">Text</label><br />
  <textarea name="text" id="text"></textarea>
  <br>
  <label for="deadline">Deadline</label><br />
  <div class="container">
    <div class="row">
            <div class="form-group">
                <div class='input-group date' id='datetimepicker1'>
                    <input type="text" name="deadline" id="datetime" class="form-control" />
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
        <script type="text/javascript">
        $(function () {
              $('#datetimepicker1').datetimepicker();
              });
        </script>
    </div>
    </div>
  <br>
  <label for="group">Group</label><br />
  <input type="text" name="group" id="group" />
  <br>
  <label for="priority">Priority</label><br />
  <select name="priority">
     <option value="High">High</option>
     <option value="Medium">Medium</option>
     <option value="Low">Low</option>
  </select>
  <br>
  <label for="priority">Users(who have access)</label><br />
  <select name="users" id="some-select" multiple="multiple">
    {% for user in users %}
        {% if not user.username == current_user.username %}
          <option value="{{user.username}}">{{user.username}}</option>
        {% endif %}
    {% endfor %}
  </select>
  <br><br>
   <font color="black"><input type="submit" value="Submit" /></font>
</form>
<br>
<a href="/tasktracker"><< Go Back</a>
</div>
</font>
{% include 'partials/footer.html' %}

tracker/tasktracker/templates/tasktracker/detail.html
{% include 'partials/header.html' %}
<div align="center">
 <font class="lead" color="lightgrey">
  <a href="/tasktracker" ><font color="white"><< Go Back</font></a>
  {%if not task.state == 'Ready'%}
  <br>
  <a class="btn btn-sm btn-primary" href="{% url 'tasktracker:complete' task.id %}">Complete</a>
  {%endif%}
  <br>
  <h5>Title:</h5>
  <h5>{{task.title}}</h5>
  <label for="title">Discription:</label><br />
  <p>{{task.body}}</p>
  <p>Group: {{task.group}}</p>
  <p>Priority: {{task.priority}}</p>
  <p>Deadline: {{task.deadline}}</p>
  <p>State: {{task.state}}
  <p>Created on {{task.timecreate}}</p>
  <p>Changed on {{task.timechange}}</p>
</font>
</div>
{% include 'partials/footer.html' %}

tracker/tasktracker/templates/tasktracker/edit.html
{% include 'partials/header.html' %}
<font color="white">
<div class="container">
<form action="{% url 'tasktracker:edit'  task.id %}" method="post">
{% csrf_token %}
{% for message in messages %}
  <div class="alert alert-success">
    <a class="close" href="#" data-dismiss="alert">×</a>
      {{ message }}
    </div>
{% endfor %}
  <label for="title">Title</label><br />
  <input type="text" name="title" id="title" value="{{task.title}}"/>
  <br>
  <label for="text">Text</label><br />
  <textarea name="text" id="text" >{{task.body}}</textarea>
  <br>
  <label for="deadline">Deadline</label><br />
  <div class="container">
    <div class="row">
            <div class="form-group">
                <div class='input-group date' id='datetimepicker1'>
                    <input  type="text" name="deadline" id="datetime"  value="{{deadline}}" class="form-control"/>
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
        <script type="text/javascript">
        $(function () {
              $('#datetimepicker1').datetimepicker();
              });
        </script>
    </div>
</div>
  <br>
  <label for="group">Group</label><br />
  <input type="text" name="group" id="group" value="{{task.group}}"/>
  <br>
  <label for="priority">Priority</label><br />
  <select name="priority">
	   <option  value="High" {% if task.priority == 'High' %}selected="selected"{% endif %} >High</option>
	   <option value="Medium" {% if task.priority == 'Medium' %}selected="selected"{% endif %} >Medium</option>
	   <option value="Low" {% if task.priority == 'Low'  %}selected="selected"{% endif %} >Low</option>
  </select>
  {{ task.users.all. }}
  {% if task.author == current_user %}
  <br>
  <label for="priority">Users(who have access)</label><br />
  <select name="users" id="some-select" multiple="multiple">
    {% for user in users %}
        {% if not user.username == current_user.username %}
          <option {% if user in task.users.all %} selected="selected" {%endif%}value="{{user.username}}">{{user.username}}</option>
        {% endif %}
    {% endfor %}
  {% endif %}
  </select>
  <br><br>
  <font color="black"><input type="submit" value="Submit" /></font>
</form>
<br>
<a href="/tasktracker"><< Go Back</a>
</div>
</font>
{% include 'partials/footer.html' %}

tracker/tasktracker/templates/tasktracker/index.html
{% include 'partials/header.html' %}
<header>
  <div class="container bg-info p-5 ">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a href="{% url 'tasktracker:add'  %}" class="btn btn-danger btn-lg" role="button">Add Task</a>
            <a href="{% url 'tasktracker:logout'  %}" class="btn btn-warning btn-lg" role="button">Log Out</a>
            <a href="{% url 'tasktracker:change_password'  %}" class="btn btn-danger btn-lg" role="button">Change Password</a>
            <a href="{% url 'tasktracker:removeuser'  %}" class="btn btn-primary btn-lg" role="button" onclick="return confirm('Are you sure you want to delete this?')">Delete Account</a>
            <a href="{% url 'tasktracker:reccurent'  %}" class="btn btn-warning btn-lg" role="button">Add Reccurent Task</a>
        </div>
      </div>
    </nav>
  </div>
</header>
<!---->
<main>
<div class="container my-5">
       <div class="card-body text-center">
         {% for message in messages %}
           <div class="alert alert-success">
             <a class="close" href="#" data-dismiss="alert">×</a>
               {{ message }}
             </div>
         {% endfor %}
  </div>
    <div class="card">
        <table class="table table-hover">
            <thead>
              <div class="container">
                <a class="btn btn-sm btn-primary" href="{% url 'tasktracker:show' 'Ready' %}"> Complete</a>
                <a class="btn btn-sm btn-primary" href="{% url 'tasktracker:show' 'Failed' %}"> Failed</a>
                <a class="btn btn-sm btn-primary" href="{% url 'tasktracker:show' 'Not Ready'%}"> Not Ready</a>
                <a class="btn btn-sm btn-primary" href="{% url 'tasktracker:index' %}"> All</a>
              </div>
              <tr>
                <th scope="col">Task Name</th>
                <th scope="col">Deadline</th>
                <th scope="col">State</th>
                <th scope="col">Group</th>
                <th scope="col">Edit Task </th>
                <th scope="col">Task Info</th>
              </tr>
            </thead>
            <tbody>
              {% for task in tasks %}
              {% if task.subtask == False %}
              <tr>
                <td>{{task}}</td>
                <td>{{task.deadline}}</td>
                <td>{{task.state}}</td>
                <td>{{task.group}}</td>
                <td>
                  <div class="container">
                    <a class="btn btn-sm btn-primary" href="{% url 'tasktracker:edit' task.id %}"><i class="far fa-edit"></i> edit</a>
                    <form class="btn btn-sm btn-primary" action="{% url 'tasktracker:delete' task.id %}" method="post">
                      {% csrf_token %}
                        <input class="btn btn-sm btn-primary" type="submit" onclick="return confirm('Are you sure you want to delete this?')" class="btn" value="delete" name="delete"/>
                   </form>
                    <a class="btn btn-sm btn-danger" href="{% url 'tasktracker:subtask' task.id %}"><i class="far fa-edit"></i>add subtask</a>
                  </div>
                </td>
                <td><a class="btn btn-sm btn-info" href="{% url 'tasktracker:detail' task.id %}"><i class="fas fa-info-circle"></i> Details</a> </td>
              </tr>
              {% for subtask in tasks %}
                {%if subtask.parent == task.id %}
                <tr>
                  <td><li>{{subtask}}</li></td>
                  <td>{{subtask.deadline}}</td>
                  <td>{{subtask.state}}</td>
                  <td>{{subtask.group}}</td>
                  <td>
                      <a class="btn btn-sm btn-primary" href="{% url 'tasktracker:edit' subtask.id %}"><i class="far fa-edit"></i> edit</a>
                      <form class="btn btn-sm btn-primary" action="{% url 'tasktracker:delete' task.id %}" method="post">
                        {% csrf_token %}
                          <input class="btn btn-sm btn-primary" type="submit" onclick="return confirm('Are you sure you want to delete this?')" class="btn" value="delete" name="delete"/>
                     </form>
                  </td>
                  <td><a class="btn btn-sm btn-info" href="{% url 'tasktracker:detail' subtask.id %}"><i class="fas fa-info-circle"></i> Details</a> </td>
                </tr>
                {%endif%}
                {% endfor %}
              {%endif%}
              {% endfor %}
            </tbody>
          </table>
    </div>
    <h2 align="center">Reccurent Tasks</h2>
    <div class="card">
        <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">Task Name</th>
                <th scope="col">Deadline</th>
                <th scope="col">State</th>
                <th scope="col">Group</th>
                <th scope="col">Edit Task </th>
                <th scope="col">Task Info</th>
              </tr>
            </thead>
            <tbody>
              {% for task in reccurenttasks %}
              <tr>
                <td>{{task}}</td>
                <td>{{task.deadline}}</td>
                <td>{{task.state}}</td>
                <td>{{task.group}}</td>
                <td>
                    <a class="btn btn-sm btn-primary" href="{% url 'tasktracker:redit' task.id %}"><i class="far fa-edit"></i> edit</a>
                    <form class="btn btn-sm btn-primary" action="{% url 'tasktracker:rdelete' task.id %}" method="post">
                      {% csrf_token %}
                        <input class="btn btn-sm btn-primary" type="submit" onclick="return confirm('Are you sure you want to delete this?')" class="btn" value="delete" name="delete"/>
                   </form>
                </td>
                <td><a class="btn btn-sm btn-info" href="{% url 'tasktracker:rdetail' task.id %}"><i class="fas fa-info-circle"></i> Details</a> </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
    </div>
    <h2 align="center">Team Tasks</h2>
    <div class="card">
        <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">Task Name</th>
                <th scope="col">Author</th>
                <th scope="col">Deadline</th>
                <th scope="col">State</th>
                <th scope="col">Group</th>
                <th scope="col">Edit Task </th>
                <th scope="col">Task Info</th>
              </tr>
            </thead>
            <tbody>
              {% for task in teamtasks %}
              {% if task.subtask == False %}
              <tr>
                <td>{{task}}</td>
                <td>{{task.author}}</td>
                <td>{{task.deadline}}</td>
                <td>{{task.state}}</td>
                <td>{{task.group}}</td>
                <td>
                    <a class="btn btn-sm btn-primary" href="{% url 'tasktracker:edit' task.id %}"><i class="far fa-edit"></i> edit</a>
                    <a class="btn btn-sm btn-danger" href="{% url 'tasktracker:subtask' task.id %}"><i class="far fa-edit"></i>add subtask</a>
                </td>
                <td><a class="btn btn-sm btn-info" href="{% url 'tasktracker:detail' task.id %}"><i class="fas fa-info-circle"></i> Details</a> </td>
              </tr>
              {% for subtask in teamtasks %}
                {%if subtask.parent == task.id %}
                <tr>
                  <td><li>{{subtask}}</li></td>
                  <td>{{subtask.author}}</td>
                  <td>{{subtask.deadline}}</td>
                  <td>{{subtask.state}}</td>
                  <td>{{subtask.group}}</td>
                  <td>
                      <a class="btn btn-sm btn-primary" href="{% url 'tasktracker:edit' subtask.id %}"><i class="far fa-edit"></i> edit</a>
                  </td>
                  <td><a class="btn btn-sm btn-info" href="{% url 'tasktracker:detail' subtask.id %}"><i class="fas fa-info-circle"></i> Details</a> </td>
                </tr>
                {%endif%}
                {% endfor %}
              {%endif%}
              {% endfor %}
            </tbody>
          </table>
    </div>
{% include 'partials/footer.html' %}

tracker/tasktracker/templates/tasktracker/rdetail.html
{% include 'partials/header.html' %}
<div align="center">
 <font class="lead" color="lightgrey">
  <a href="/tasktracker" ><font color="white"><< Go Back</font></a>
  {%if not task.state == 'Ready'%}
  <br>
  <a class="btn btn-sm btn-primary" href="{% url 'tasktracker:rcomplete' task.id %}">Complete</a>
  {%endif%}
  <br>
  <h5>Title:</h5>
  <h5>{{task.title}}</h5>
  <label for="title">Discription:</label><br />
  <p>{{task.body}}</p>
  <p>Group: {{task.group}}</p>
  <p>Priority: {{task.priority}}</p>
  <p>Deadline: {{task.deadline}}</p>
  {%if period %}
  <p>Repeat each {{task.period}} days</p>
  {%else %}
  <p>Repeat at {{days}} </p>
  {%endif%}
  <p>State: {{task.state}}
  <p>Created on {{task.timecreate}}</p>
  <p>Changed on {{task.timechange}}</p>
</font>
</div>
{% include 'partials/footer.html' %}

tracker/tasktracker/templates/tasktracker/reccurent.html
{% include 'partials/header.html' %}
<font color="white">
<div class="container">
<form action="{% url 'tasktracker:reccurent'  %}" method="post">
{% csrf_token %}
{% for message in messages %}
  <div class="alert alert-success">
    <a class="close" href="#" data-dismiss="alert">×</a>
      {{ message }}
    </div>
{% endfor %}
  <label for="title">Title</label><br />
  <input type="text" name="title" id="title" />
  <br>
  <label for="text">Text</label><br />
  <textarea name="text" id="text"></textarea>
  <br>
  <label for="deadline">Deadline</label><br />
  <div class="container">
    <div class="row">
            <div class="form-group">
                <div class='input-group date' id='datetimepicker1'>
                    <input type="text" name="deadline" id="datetime" class="form-control" />
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
        <script type="text/javascript">
        $(function () {
              $('#datetimepicker1').datetimepicker();
              });
        </script>
    </div>
    </div>
  <br>
  <label for="priority">How often repeat(days):</label><br />
<input type="number" name="period" id="input" min="0" value="">
<br>
<label for="priority">When repeat(weekday):</label><br />
<select name="weekdays" id="some-select" multiple="multiple">
    <option value="0">Monday</option>
    <option value="1">Tuesday</option>
    <option value="2">Wednesday</option>
    <option value="3">Thursday</option>
    <option value="4">Friday</option>
    <option value="5">Saturday</option>
    <option value="6">Sunday</option>
</select>
<br>
  <label for="group">Group</label><br />
  <input type="text" name="group" id="group" />
  <br>
  <label for="priority">Priority</label><br />
  <select name="priority">
     <option value="High">High</option>
     <option value="Medium">Medium</option>
     <option value="Low">Low</option>
  </select>
  <br><br>
   <font color="black"><input type="submit" value="Submit" /></font>
</form>
<br>
<a href="/tasktracker"><< Go Back</a>
</div>
</font>
{% include 'partials/footer.html' %}

tracker/tasktracker/templates/tasktracker/subtask.html
{% include 'partials/header.html' %}
<font color="white">
<div class="container">
<form action="{% url 'tasktracker:subtask'  task.id %}" method="post">
{% csrf_token %}
{% for message in messages %}
  <div class="alert alert-success">
    <a class="close" href="#" data-dismiss="alert">×</a>
      {{ message }}
    </div>
{% endfor %}
  <label for="title">Title</label><br />
  <input type="text" name="title" id="title" />
  <br>
  <label for="text">Text</label><br />
  <textarea name="text" id="text"></textarea>
  <br>
  <label for="deadline">Deadline</label><br />
  <div class="container">
    <div class="row">
            <div class="form-group">
                <div class='input-group date' id='datetimepicker1'>
                    <input type="text" name="deadline" id="datetime" class="form-control" />
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
        <script type="text/javascript">
        $(function () {
              $('#datetimepicker1').datetimepicker();
              });
        </script>
    </div>
</div>
  <br>
  <label for="group">Group</label><br />
  <input type="text" name="group" id="group" />
  <br>
  <label for="priority">Priority</label><br />
  <select name="priority">
     <option value="High">High</option>
     <option value="Medium">Medium</option>
     <option value="Low">Low</option>
  </select>
  <br><br>
  <font color="black"><input type="submit" value="Submit" /></font>
</form>
<br>
<a href="/tasktracker"><< Go Back</a>
</div>
</font>
{% include 'partials/footer.html' %}